# Memory Settings
'shared_buffers': '8192MB',
'work_mem': '32MB',
'maintenance_work_mem': '520MB',
'huge_pages': 'try',
'effective_cache_size': '22GB',
'effective_io_concurrency': '1',
'random_page_cost': '4.0',

# Replication
'wal_level': 'replica',
'max_wal_senders': '0',
'synchronous_commit': 'on',

# Checkpointing
'checkpoint_timeout': '15min',
'checkpoint_completion_target': '0.9',
'max_wal_size': '1024MB',
'min_wal_size': '512MB',

# WAL writing
'wal_compression': 'on',
'wal_buffers': '-1',
'wal_writer_delay': '200ms',
'wal_writer_flush_after': '1MB',

# Background writer
'bgwriter_delay': '200ms',
'bgwriter_lru_maxpages': '100',
'bgwriter_lru_multiplier': '2.0',
'bgwriter_flush_after': '0',

# Parallel queries
'max_worker_processes': '12',
'max_parallel_workers_per_gather': '6',
'max_parallel_maintenance_workers': '6',
'max_parallel_workers': '12',
'parallel_leader_participation': 'on',

# Advanced features
'enable_partitionwise_join': 'on',
'enable_partitionwise_aggregate': 'on',
'jit': 'on',
'max_slot_wal_keep_size': '1000MB',
'track_wal_io_timing': 'on',
'maintenance_io_concurrency': '1',
'wal_recycle': 'on'